version: 2.1

jobs:
  test:
    parameters:
      tag:
        type: string
      ref:
        type: string
      param:
        type: string
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: "Setup required directories"
        command: |
          mkdir -p /tmp/apache-cloudstack
          mkdir -p /tmp/.m2
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-m2
    - run:
        name: "Build Docker image"
        command: make <<parameters.tag>>
    - run:
        name: "Test Docker image"
        command: |
          docker run \
            --volume /tmp/apache-cloudstack:/mnt/build \
            --volume /tmp/.m2:/root/.m2 \
            --rm \
            khos2ow/cloudstack-deb-builder:<<parameters.tag>> \
              --git-remote https://github.com/apache/cloudstack.git \
              --git-ref <<parameters.ref>> \
              --remove-first \
              <<parameters.param>>
    - save_cache:
        key: repo-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-m2
        paths:
          - /tmp/.m2

  push:
    parameters:
      tag:
        type: string
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Push docker image
        command: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          DOCKER_TAG=<<parameters.tag>> make <<parameters.tag>> push

workflows:
  version: 2
  test:
    jobs:
    - test:
        name: test-ubuntu1404
        tag: ubuntu1404
        ref: refs/heads/4.13
        param: ""
        filters:
          branches:
            ignore: master

    - test:
        name: test-ubuntu1604
        tag: ubuntu1604
        ref: refs/heads/4.13
        param: ""
        filters:
          branches:
            ignore: master

    - test:
        name: test-ubuntu1804
        tag: ubuntu1804
        ref: refs/heads/4.13
        param: ""
        filters:
          branches:
            ignore: master
    
    - test:
        name: test-ubuntu1804-jdk11
        tag: ubuntu1804-jdk11
        ref: refs/heads/4.15
        param: ""
        filters:
          branches:
            ignore: master

  build:
    jobs:
    - push:
        name: push-ubuntu1404
        tag: ubuntu1404
        filters:
          branches:
            only: master

    - push:
        name: push-ubuntu1604
        tag: ubuntu1604
        filters:
          branches:
            only: master

    - push:
        name: push-ubuntu1804
        tag: ubuntu1804
        filters:
          branches:
            only: master
    
    - push:
        name: push-ubuntu1804-jdk11
        tag: ubuntu1804-jdk11
        filters:
          branches:
            only: master

    - push:
        name: push-latest
        tag: latest
        filters:
          branches:
            only: master
